### ISSUE TITLE
一定時間経過後、コマンドを受け付けない

### ISSUE THREAD

**Issue by BYODKM** [hirosan18/homebridge-nature-remo#3]
一定時間経過後、コマンドを受け付けなくなるようだったので、調べてみたのですが、

https://github.com/hirosan18/homebridge-nature-remo/blob/f0f09ff97a425907b0f54cba28c2efc0d4242491/index.js#L46-L55

`config.on` 内のコマンドが `string` だけだと`delay` が `undefined` になるので、`sleep`に `NaN`を渡しているかもです。

https://github.com/hirosan18/homebridge-nature-remo/blob/f0f09ff97a425907b0f54cba28c2efc0d4242491/index.js#L117-L119

**Comment by hirosan18** [comment]
報告ありがとうございます。確認してみます！

**Comment by hirosan18** [comment]
@BYODKM 

コードに関してですが、たしかに問題になりそうな感じはするので修正しておきます！

ただ、過去にも同じような問題が起きている方がいて、
調査した結果、NatureRemoのファームウェアの不具合だったというケースがあり、
同様の現象が起きていないか↓のIssue確認してもらってもよろしいでしょうか？
https://github.com/hirosan18/homebridge-nature-remo/issues/1

**Comment by hirosan18** [comment]
`sleep` の内部を見てみたんですが、 中で `setTimeout` をやってるだけなので、
`setTimeout` に `NaN` や `undefined` を渡しても即時実行される(0を指定したときと同じ挙動をする)はずなので、
原因は違うところにありそうです。

**Comment by BYODKM** [comment]
確認ありがとうございます。

Config.jsonで `"on"` と `"off"` を `string[]` から`object[]`にして、 `"delay": 100` を与えてみたところ、かなり安定して稼働し始めたので、これか！と思ったのですが、その後、また無反応になることがあり、完璧じゃないことが分かりました。

問題発生の前後で、`curl` で `/status` を叩いてみましたが、今のところ変化はないようです。 （`"status": 8`)

ちなみに、環境はMac miniで、OSはCatalinaになります。（スリープはしない設定）
`homebridge-config-ui-x` も怪しかったので、`v12.18.2` のNodeをnodebrew経由で入れ直して、インストールしているパッケージは`homebridge` と `homebridge-nature-remo` だけになっています。

一旦、ご報告まで。

**Comment by BYODKM** [comment]
どうやらハードの問題だったらしく、二台あるうちの古い方をネットワークから外したら安定稼働し始めました。
お騒がせして、申し訳ありませんでした。

ソフトウェアまわりをアップデートしたタイミングと同時期に古い方が不調をきたしだしたらしく、問題の矛先を見誤りました。 
以後、気をつけます。🙇‍♂️

**Comment by hirosan18** [comment]
@BYODKM 

> どうやらハードの問題だったらしく、二台あるうちの古い方をネットワークから外したら安定稼働し始めました。

ちゃんと動いてよかったです🙌
ハードの当たり外れあるっぽいのかわからないですが、新しいRemoで直ってるといいですね〜

また何かあればIssueください！これはCloseします！！
